credentials:
  usernames:
    abhikhand:
      email: abhi.khandel12@gmail.com
      name: Abhimanyu Khandelwal
      password: '$2b$12$PC0l8fPJyCOUU5IGwr280OteUiSGjgeLs0IrF214fXsssi.Gf6yRK'

cookie:
  expiry_days: 30
  key: 'dingdong12345' 
  name: 'talentreach_auth_cookie'